language: minimal
sudo: required
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - docker pull grimkriegor/tes3mp-forge
script:
  - /bin/bash ./tes3mp-deploy.sh --container --commit stable --install --make-package
